apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config

data:
  NODE_ENV: 'production'
  HTTP_PORT: '8080'
  BSV_NETWORK: 'main'
  ENABLE_NGINX: 'false'
  WALLET_STORAGE_TRUST_PROXY_HOPS: '1'
  WALLET_STORAGE_MONITOR_START_TASKS: 'true'
  WALLET_STORAGE_MONITOR_STARTUP_TASK_MODE: 'default'
  WALLET_STORAGE_MONITOR_ADMIN_ENABLED: 'false'
