import * as sdk from '../../sdk'
import { StorageIdb } from '../StorageIdb'

const provenTxReqStatusesSafeForInputRestore = new Set<sdk.ProvenTxReqStatus>(['invalid', 'doubleSpend'])

/**
 * 1. set transactions to 'failed' if not already failed and provenTxReq with matching txid has status of 'invalid'.
 */
async function failTransactionsForInvalidReqs (storage: StorageIdb, r: { log: string }): Promise<void> {
  const invalidTxids: string[] = []
  await storage.filterProvenTxReqs({ partial: { status: 'invalid' } }, txReq => {
    invalidTxids.push(txReq.txid)
  })
  for (const txid of invalidTxids) {
    const txs = await storage.findTransactions({ partial: { txid } })
    for (const tx of txs) {
      if (tx.status !== 'failed') {
        r.log += `transaction ${tx.transactionId} updated to status of 'failed' was ${tx.status}\n`
        await storage.updateTransactionStatus('failed', tx.transactionId)
      }
    }
  }
}

/**
 * Partitions failed transactions into all failed ids and the subset that is safe for input restore
 * (terminal failure: no blocking ProvenTxReq, i.e. all reqs are 'invalid'/'doubleSpend').
 */
async function collectFailedTransactionIds (
  storage: StorageIdb
): Promise<{ failedTransactionIds: Set<number>, safeFailedTransactionIds: Set<number> }> {
  const failedTxs = await storage.findTransactions({ partial: { status: 'failed' }, noRawTx: true })
  const failedTransactionIds = new Set<number>()
  const safeFailedTransactionIds = new Set<number>()
  for (const tx of failedTxs) {
    failedTransactionIds.add(tx.transactionId)
    let hasBlockingReq = false
    if (tx.txid != null && tx.txid !== '') {
      const reqs = await storage.findProvenTxReqs({ partial: { txid: tx.txid } })
      hasBlockingReq = reqs.some(req => !provenTxReqStatusesSafeForInputRestore.has(req.status))
    }
    if (!hasBlockingReq) safeFailedTransactionIds.add(tx.transactionId)
  }
  return { failedTransactionIds, safeFailedTransactionIds }
}

/**
 * Looks for unpropagated state:
 *
 * 1. set transactions to 'failed' if not already failed and provenTxReq with matching txid has status of 'invalid'.
 * 2. sets outputs to spendable true, spentBy undefined if spentBy is a terminal failed transaction.
 * 3. sets outputs generated by terminal failed transactions to spendable false, spentBy undefined.
 *
 * @param storage
 * @param args
 * @returns
 */
export async function reviewStatusIdb (
  storage: StorageIdb,
  args: { agedLimit: Date, trx?: sdk.TrxToken }
): Promise<{ log: string }> {
  const r: { log: string } = { log: '' }

  await failTransactionsForInvalidReqs(storage, r)

  const { failedTransactionIds, safeFailedTransactionIds } = await collectFailedTransactionIds(storage)

  const outputs = await storage.findOutputs({ partial: {}, trx: args.trx })
  for (const output of outputs) {
    // An output generated by any failed tx (even one still reconcilable from an active req) is
    // not a valid input to restore, matching the SQL `source.status = 'failed'` guard.
    const generatedByFailedTx = failedTransactionIds.has(output.transactionId)
    const generatedBySafeFailedTx = safeFailedTransactionIds.has(output.transactionId)
    const spentBySafeFailedTx = output.spentBy != null && safeFailedTransactionIds.has(output.spentBy)

    if (spentBySafeFailedTx && !generatedByFailedTx) {
      await storage.updateOutput(output.outputId, { spendable: true, spentBy: undefined }, args.trx)
      r.log += `output ${output.outputId} updated to spendable because spentBy is failed\n`
    }

    if (generatedBySafeFailedTx && (output.spendable || output.spentBy != null)) {
      await storage.updateOutput(output.outputId, { spendable: false, spentBy: undefined }, args.trx)
      r.log += `output ${output.outputId} updated to not spendable because transaction is failed\n`
    }
  }

  return r
}
