import * as sdk from '../../sdk'
import { StorageIdb } from '../StorageIdb'

const provenTxReqStatusesSafeForInputRestore: sdk.ProvenTxReqStatus[] = ['invalid', 'doubleSpend']

/**
 * Looks for unpropagated state:
 *
 * 1. set transactions to 'failed' if not already failed and provenTxReq with matching txid has status of 'invalid'.
 * 2. sets transactions to 'completed' if provenTx with matching txid exists and current provenTxId is null.
 * 3. sets outputs to spendable true, spentBy undefined if spentBy is a terminal failed transaction.
 * 4. sets outputs generated by terminal failed transactions to spendable false, spentBy undefined.
 *
 * @param storage
 * @param args
 * @returns
 */
export async function reviewStatusIdb (
  storage: StorageIdb,
  args: { agedLimit: Date, trx?: sdk.TrxToken }
): Promise<{ log: string }> {
  const r: { log: string } = { log: '' }

  // 1. set transactions to 'failed' if not already failed and provenTxReq with matching txid has status of 'invalid'.
  const invalidTxids: string[] = []
  await storage.filterProvenTxReqs({ partial: { status: 'invalid' } }, txReq => {
    invalidTxids.push(txReq.txid)
  })
  for (const txid of invalidTxids) {
    const txs = await storage.findTransactions({ partial: { txid } })
    for (const tx of txs) {
      if (tx.status !== 'failed') {
        r.log += `transaction ${tx.transactionId} updated to status of 'failed' was ${tx.status}\n`
        await storage.updateTransactionStatus('failed', tx.transactionId)
      }
    }
  }

  const failedTxs = await storage.findTransactions({
    partial: { status: 'failed' },
    noRawTx: true
  })
  const safeFailedTransactionIds = new Set<number>()
  for (const tx of failedTxs) {
    let hasBlockingReq = false
    if (tx.txid != null && tx.txid !== '') {
      const reqs = await storage.findProvenTxReqs({ partial: { txid: tx.txid } })
      hasBlockingReq = reqs.some(req => !provenTxReqStatusesSafeForInputRestore.includes(req.status))
    }
    if (!hasBlockingReq) safeFailedTransactionIds.add(tx.transactionId)
  }

  const outputs = await storage.findOutputs({ partial: {}, trx: args.trx })
  for (const output of outputs) {
    const generatedBySafeFailedTx = safeFailedTransactionIds.has(output.transactionId)
    const spentBySafeFailedTx = output.spentBy != null && safeFailedTransactionIds.has(output.spentBy)

    if (spentBySafeFailedTx && !generatedBySafeFailedTx) {
      await storage.updateOutput(output.outputId, { spendable: true, spentBy: undefined }, args.trx)
      r.log += `output ${output.outputId} updated to spendable because spentBy is failed\n`
    }

    if (generatedBySafeFailedTx && (output.spendable || output.spentBy != null)) {
      await storage.updateOutput(output.outputId, { spendable: false, spentBy: undefined }, args.trx)
      r.log += `output ${output.outputId} updated to not spendable because transaction is failed\n`
    }
  }

  return r
}
