import fc from 'fast-check'
import { readBrc38JsonStream, type Brc38JsonStagingSink } from './Brc38JsonStream'
import { jsonStreamFixture } from './Brc38JsonStreamFixture'
import { parseBRC38Json, type BRC38Tables } from './index'

const MIN_PROPERTY_RUNS = 300
fc.configureGlobal({
  numRuns: Math.max(MIN_PROPERTY_RUNS, Number(process.env.FAST_CHECK_NUM_RUNS ?? MIN_PROPERTY_RUNS)),
  seed: Number(process.env.FAST_CHECK_SEED ?? 3242026),
  ...(process.env.FAST_CHECK_PATH ? { path: process.env.FAST_CHECK_PATH } : {}),
  interruptAfterTimeLimit: 150000,
  markInterruptAsFailure: true
})

const SEED = Number(process.env.FAST_CHECK_SEED ?? 3242026)
test('generated byte partitions, table/root order and row counts agree with the legacy semantic oracle', async () => {
  await fc.assert(
    fc.asyncProperty(
      fc.record({
        width: fc.integer({ min: 1, max: 4096 }),
        reverse: fc.boolean(),
        rows: fc.integer({ min: 0, max: 12 }),
        text: fc
          .array(fc.constantFrom('a', '🙂', '\u0000', '\\', '"', 'é', ' ', '\n'), { maxLength: 30 })
          .map(values => values.join(''))
      }),
      async sample => {
        const document = jsonStreamFixture()
        document.tables.txLabels = Array.from({ length: sample.rows }, (_value, index) => ({
          userId: 7,
          txLabelId: 100 + index,
          label: sample.text + index,
          isDeleted: index % 2 === 0
        }))
        document.tables.txLabelMaps = []
        const ordered = sample.reverse ? Object.fromEntries(Object.entries(document).reverse()) : document
        const text = JSON.stringify(ordered),
          bytes = new TextEncoder().encode(text)
        const staged = jsonStreamFixture().tables
        for (const table of Object.keys(staged) as Array<keyof BRC38Tables>) staged[table] = []
        let completed = false,
          discarded = false
        const sink: Brc38JsonStagingSink = {
          async provisionalRow(table, index, row) {
            expect(index).toBe(staged[table].length)
            staged[table].push(row)
          },
          async validateCompleted(header, counts) {
            expect(parseBRC38Json(JSON.stringify({ ...header, tables: staged }))).toEqual(parseBRC38Json(text))
            for (const table of Object.keys(staged) as Array<keyof BRC38Tables>)
              expect(counts[table]).toBe(staged[table].length)
            completed = true
          },
          async discard() {
            discarded = true
          }
        }
        async function* input() {
          for (let offset = 0; offset < bytes.length; offset += sample.width)
            yield bytes.slice(offset, offset + sample.width)
        }
        const result = await readBrc38JsonStream(input(), sink, {
          maximumArchiveBytes: 1048576,
          maximumRowAllocationBytes: 65536
        })
        expect(result.inputBytes).toBe(bytes.length)
        expect(completed).toBe(true)
        expect(discarded).toBe(false)
      }
    ),
    {
      numRuns: Math.max(MIN_PROPERTY_RUNS, Number(process.env.FAST_CHECK_NUM_RUNS ?? MIN_PROPERTY_RUNS)),
      seed: SEED,
      endOnFailure: true,
      interruptAfterTimeLimit: 150000,
      markInterruptAsFailure: true
    }
  )
}, 180000)

test('generated truncation and early-source completion never validate private staging', async () => {
  const text = JSON.stringify(jsonStreamFixture()),
    bytes = new TextEncoder().encode(text)
  await fc.assert(
    fc.asyncProperty(
      fc.integer({ min: 0, max: bytes.length - 1 }),
      fc.integer({ min: 1, max: 1024 }),
      async (cut, width) => {
        let rows = 0,
          complete = false,
          discarded = false,
          closed = false
        const sink: Brc38JsonStagingSink = {
          async provisionalRow() {
            rows++
          },
          async validateCompleted() {
            complete = true
          },
          async discard() {
            expect(closed).toBe(true)
            discarded = true
          }
        }
        async function* input() {
          try {
            for (let offset = 0; offset < cut; offset += width) yield bytes.slice(offset, Math.min(cut, offset + width))
          } finally {
            closed = true
          }
        }
        await expect(
          readBrc38JsonStream(input(), sink, { maximumArchiveBytes: 1048576, maximumRowAllocationBytes: 65536 })
        ).rejects.toThrow()
        expect(complete).toBe(false)
        expect(discarded).toBe(true)
        expect(rows).toBeLessThanOrEqual(13)
        expect(() => parseBRC38Json(Buffer.from(bytes.subarray(0, cut)).toString())).toThrow()
      }
    ),
    {
      numRuns: Math.max(MIN_PROPERTY_RUNS, Number(process.env.FAST_CHECK_NUM_RUNS ?? MIN_PROPERTY_RUNS)),
      seed: SEED,
      endOnFailure: true,
      interruptAfterTimeLimit: 150000,
      markInterruptAsFailure: true
    }
  )
}, 180000)
