import { _tu } from '../utils/TestUtilsWalletStorage'
import type { TransactionStatus } from '../../src/sdk/types'
import type { StorageProvider } from '../../src/storage/StorageProvider'
import type { TableOutput, TableTransaction } from '../../src/storage/schema/tables'

interface FailedTransactionOutputState {
  failedTx: TableTransaction
  generatedOutput: TableOutput
  inputOutput: TableOutput
}

export async function seedFailedTransactionOutputState (
  storage: StorageProvider,
  status: TransactionStatus
): Promise<FailedTransactionOutputState> {
  const { tx: fundingTx, user } = await _tu.insertTestTransaction(storage, undefined, false, {
    status: 'completed',
    txid: 'b'.repeat(64)
  })
  const { tx: failedTx } = await _tu.insertTestTransaction(storage, user, false, {
    status,
    txid: status === 'failed' ? 'c'.repeat(64) : undefined
  })
  const inputOutput = await _tu.insertTestOutput(storage, fundingTx, 0, 1000, undefined, false, {
    spendable: false,
    spentBy: failedTx.transactionId
  })
  const generatedOutput = await _tu.insertTestOutput(storage, failedTx, 0, 900, undefined, false, {
    spendable: true,
    spentBy: failedTx.transactionId
  })

  return { failedTx, generatedOutput, inputOutput }
}

export async function expectFailedTransactionOutputStateRepaired (
  storage: StorageProvider,
  state: FailedTransactionOutputState
): Promise<void> {
  const inputAfter = await findOneOutput(storage, state.inputOutput.outputId)
  expect(inputAfter.spendable).toBe(true)
  expect(inputAfter.spentBy).toBeUndefined()

  const generatedAfter = await findOneOutput(storage, state.generatedOutput.outputId)
  expect(generatedAfter.spendable).toBe(false)
  expect(generatedAfter.spentBy).toBeUndefined()
}

interface ReconcilableSourceOutputState {
  reconcilableFailedTx: TableTransaction
  safeFailedTx: TableTransaction
  generatedOutput: TableOutput
}

/**
 * Seeds an output generated by a failed-but-still-reconcilable transaction (it has a blocking,
 * non-terminal ProvenTxReq) that is spent-by a separate terminal (safe) failed transaction.
 *
 * Such an output must NOT be restored to spendable: it was generated by a failed tx, so it is not
 * a valid input to restore even though its spender is a safe failed tx. Both the SQL and IDB
 * reviewStatus paths must agree here.
 */
export async function seedReconcilableSourceOutputState (
  storage: StorageProvider
): Promise<ReconcilableSourceOutputState> {
  const reconcilableTxid = 'd'.repeat(64)
  const { tx: reconcilableFailedTx, user } = await _tu.insertTestTransaction(storage, undefined, false, {
    status: 'failed',
    txid: reconcilableTxid
  })
  // A non-terminal req (status 'nosend') makes the failed tx still reconcilable, i.e. NOT safe for input restore.
  await _tu.insertTestProvenTxReq(storage, reconcilableTxid)
  const { tx: safeFailedTx } = await _tu.insertTestTransaction(storage, user, false, {
    status: 'failed',
    txid: 'e'.repeat(64)
  })
  const generatedOutput = await _tu.insertTestOutput(storage, reconcilableFailedTx, 0, 900, undefined, false, {
    spendable: false,
    spentBy: safeFailedTx.transactionId
  })

  return { reconcilableFailedTx, safeFailedTx, generatedOutput }
}

export async function expectReconcilableSourceOutputUnchanged (
  storage: StorageProvider,
  state: ReconcilableSourceOutputState
): Promise<void> {
  const generatedAfter = await findOneOutput(storage, state.generatedOutput.outputId)
  // Generated by a failed tx => never restored to spendable; spender is not a terminal failure of
  // this output's own tx => not neutralized either. State must be left untouched.
  expect(generatedAfter.spendable).toBe(false)
  expect(generatedAfter.spentBy).toBe(state.safeFailedTx.transactionId)
}

async function findOneOutput (storage: StorageProvider, outputId: number): Promise<TableOutput> {
  const outputs = await storage.findOutputs({ partial: { outputId } })
  expect(outputs).toHaveLength(1)
  return outputs[0]
}
