import { _tu, setLogging } from '../utils/TestUtilsWalletStorage'
import { StorageProvider, verifyOne } from '../../src/index.all'
import type { ProvenTxReqStatus } from '../../src/sdk/types'

setLogging(false)

describe('reviewStatus tests', () => {
  jest.setTimeout(99999999)

  const failedTxid = 'a'.repeat(64)
  const blockingReqStatuses: ProvenTxReqStatus[] = [
    'sending',
    'unsent',
    'nosend',
    'unknown',
    'nonfinal',
    'unprocessed',
    'unmined',
    'callback',
    'unconfirmed',
    'completed',
    'unfail'
  ]

  let storages: StorageProvider[]

  beforeEach(async () => {
    storages = await _tu.createTestStorages({
      databasePrefix: 'reviewStatus',
      migrationName: 'reviewStatus tests'
    })
  })

  afterEach(async () => {
    for (const storage of storages) {
      await storage.destroy()
    }
  })

  async function seedFailedSpend (storage: StorageProvider, reqStatus?: ProvenTxReqStatus) {
    const { tx: fundingTx, user } = await _tu.insertTestTransaction(storage, undefined, false, {
      status: 'completed',
      txid: 'b'.repeat(64)
    })
    const { tx: failedTx } = await _tu.insertTestTransaction(storage, user, false, {
      status: 'failed',
      txid: failedTxid
    })
    const spentOutput = await _tu.insertTestOutput(storage, fundingTx, 0, 1000, undefined, false, {
      spendable: false,
      spentBy: failedTx.transactionId
    })

    if (reqStatus != null) {
      const req = await _tu.insertTestProvenTxReq(storage, failedTxid)
      await storage.updateProvenTxReq(req.provenTxReqId, { status: reqStatus })
    }

    return { failedTx, spentOutput }
  }

  async function seedFailedGeneratedOutput (storage: StorageProvider, reqStatus?: ProvenTxReqStatus) {
    const { failedTx } = await seedFailedSpend(storage, reqStatus)
    const generatedOutput = await _tu.insertTestOutput(storage, failedTx, 0, 2000, undefined, false, {
      spendable: true,
      spentBy: failedTx.transactionId
    })

    return { failedTx, generatedOutput }
  }

  test.each(blockingReqStatuses)('does not restore failed transaction inputs while req status is %s', async status => {
    for (const storage of storages) {
      const { failedTx, spentOutput } = await seedFailedSpend(storage, status)

      await storage.reviewStatus({ agedLimit: new Date() })

      const output = verifyOne(await storage.findOutputs({ partial: { outputId: spentOutput.outputId } }))
      expect(output.spendable).toBe(false)
      expect(output.spentBy).toBe(failedTx.transactionId)
    }
  })

  test.each([
    { label: 'no req', status: undefined },
    { label: 'invalid req', status: 'invalid' as ProvenTxReqStatus },
    { label: 'doubleSpend req', status: 'doubleSpend' as ProvenTxReqStatus }
  ])('restores failed transaction inputs with $label', async ({ status }) => {
    for (const storage of storages) {
      const { spentOutput } = await seedFailedSpend(storage, status)

      await storage.reviewStatus({ agedLimit: new Date() })

      const output = verifyOne(await storage.findOutputs({ partial: { outputId: spentOutput.outputId } }))
      expect(output.spendable).toBe(true)
      expect(output.spentBy).toBeUndefined()
    }
  })

  test.each([
    { label: 'no req', status: undefined },
    { label: 'invalid req', status: 'invalid' as ProvenTxReqStatus },
    { label: 'doubleSpend req', status: 'doubleSpend' as ProvenTxReqStatus }
  ])('neutralizes outputs generated by failed transactions with $label', async ({ status }) => {
    for (const storage of storages) {
      const { generatedOutput } = await seedFailedGeneratedOutput(storage, status)

      await storage.reviewStatus({ agedLimit: new Date() })

      const output = verifyOne(await storage.findOutputs({ partial: { outputId: generatedOutput.outputId } }))
      expect(output.spendable).toBe(false)
      expect(output.spentBy).toBeUndefined()
    }
  })

  test.each(blockingReqStatuses)('does not neutralize failed transaction outputs while req status is %s', async status => {
    for (const storage of storages) {
      const { failedTx, generatedOutput } = await seedFailedGeneratedOutput(storage, status)

      await storage.reviewStatus({ agedLimit: new Date() })

      const output = verifyOne(await storage.findOutputs({ partial: { outputId: generatedOutput.outputId } }))
      expect(output.spendable).toBe(true)
      expect(output.spentBy).toBe(failedTx.transactionId)
    }
  })
})
